<?php
/**
 * FlightSearchBookingInfo
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * FlightSearchBookingInfo Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FlightSearchBookingInfo implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'FlightSearchBookingInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'travel_class' => 'string',
        'cabin_code' => 'string',
        'booking_code' => 'string',
        'seats_remaining' => 'string',
        'fare_family' => 'string',
        'fare_basis' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'travel_class' => null,
        'cabin_code' => null,
        'booking_code' => null,
        'seats_remaining' => null,
        'fare_family' => null,
        'fare_basis' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'travel_class' => 'travel_class',
        'cabin_code' => 'cabin_code',
        'booking_code' => 'booking_code',
        'seats_remaining' => 'seats_remaining',
        'fare_family' => 'fare_family',
        'fare_basis' => 'fare_basis'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'travel_class' => 'setTravelClass',
        'cabin_code' => 'setCabinCode',
        'booking_code' => 'setBookingCode',
        'seats_remaining' => 'setSeatsRemaining',
        'fare_family' => 'setFareFamily',
        'fare_basis' => 'setFareBasis'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'travel_class' => 'getTravelClass',
        'cabin_code' => 'getCabinCode',
        'booking_code' => 'getBookingCode',
        'seats_remaining' => 'getSeatsRemaining',
        'fare_family' => 'getFareFamily',
        'fare_basis' => 'getFareBasis'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['travel_class'] = isset($data['travel_class']) ? $data['travel_class'] : null;
        $this->container['cabin_code'] = isset($data['cabin_code']) ? $data['cabin_code'] : null;
        $this->container['booking_code'] = isset($data['booking_code']) ? $data['booking_code'] : null;
        $this->container['seats_remaining'] = isset($data['seats_remaining']) ? $data['seats_remaining'] : null;
        $this->container['fare_family'] = isset($data['fare_family']) ? $data['fare_family'] : null;
        $this->container['fare_basis'] = isset($data['fare_basis']) ? $data['fare_basis'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['travel_class'] === null) {
            $invalid_properties[] = "'travel_class' can't be null";
        }
        if ($this->container['booking_code'] === null) {
            $invalid_properties[] = "'booking_code' can't be null";
        }
        if ($this->container['seats_remaining'] === null) {
            $invalid_properties[] = "'seats_remaining' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['travel_class'] === null) {
            return false;
        }
        if ($this->container['booking_code'] === null) {
            return false;
        }
        if ($this->container['seats_remaining'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets travel_class
     * @return string
     */
    public function getTravelClass()
    {
        return $this->container['travel_class'];
    }

    /**
     * Sets travel_class
     * @param string $travel_class The cabin class offered on this flight. An enumeration that will read either ECONOMY, PREMIUM_ECONOMY, BUSINESS or FIRST
     * @return $this
     */
    public function setTravelClass($travel_class)
    {
        $this->container['travel_class'] = $travel_class;

        return $this;
    }

    /**
     * Gets cabin_code
     * @return string
     */
    public function getCabinCode()
    {
        return $this->container['cabin_code'];
    }

    /**
     * Sets cabin_code
     * @param string $cabin_code A single character encoding of the travel_class, generally only available on responses from affiliates.
     * @return $this
     */
    public function setCabinCode($cabin_code)
    {
        $this->container['cabin_code'] = $cabin_code;

        return $this;
    }

    /**
     * Gets booking_code
     * @return string
     */
    public function getBookingCode()
    {
        return $this->container['booking_code'];
    }

    /**
     * Sets booking_code
     * @param string $booking_code The Reservation Booking Designator code that determines the quality and terms of the flight offered for the given price. A single letter from A..Z
     * @return $this
     */
    public function setBookingCode($booking_code)
    {
        $this->container['booking_code'] = $booking_code;

        return $this;
    }

    /**
     * Gets seats_remaining
     * @return string
     */
    public function getSeatsRemaining()
    {
        return $this->container['seats_remaining'];
    }

    /**
     * Sets seats_remaining
     * @param string $seats_remaining The minimum number of seats that are still available for this price at the time of search. If the value is a 4 or above, there are often more than this number of seats still available.
     * @return $this
     */
    public function setSeatsRemaining($seats_remaining)
    {
        $this->container['seats_remaining'] = $seats_remaining;

        return $this;
    }

    /**
     * Gets fare_family
     * @return string
     */
    public function getFareFamily()
    {
        return $this->container['fare_family'];
    }

    /**
     * Sets fare_family
     * @param string $fare_family Enumeration of the type of fare which this airline is providing, eg. VALUE. This is generally only available for affiliate responses.
     * @return $this
     */
    public function setFareFamily($fare_family)
    {
        $this->container['fare_family'] = $fare_family;

        return $this;
    }

    /**
     * Gets fare_basis
     * @return string
     */
    public function getFareBasis()
    {
        return $this->container['fare_basis'];
    }

    /**
     * Sets fare_basis
     * @param string $fare_basis See https://en.wikipedia.org/wiki/Fare_basis_code for the fare being offered.
     * @return $this
     */
    public function setFareBasis($fare_basis)
    {
        $this->container['fare_basis'] = $fare_basis;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


