<?php
/**
 * TrainSearchPricing
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * TrainSearchPricing Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TrainSearchPricing implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'TrainSearchPricing';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'service_class' => 'string',
        'booking_code' => 'string',
        'accomodation' => 'string',
        'total_price' => '\Swagger\Client\Model\Amount',
        'rate' => '\Swagger\Client\Model\RestrictedRate'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'service_class' => null,
        'booking_code' => null,
        'accomodation' => null,
        'total_price' => null,
        'rate' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'service_class' => 'service_class',
        'booking_code' => 'booking_code',
        'accomodation' => 'accomodation',
        'total_price' => 'total_price',
        'rate' => 'rate'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'service_class' => 'setServiceClass',
        'booking_code' => 'setBookingCode',
        'accomodation' => 'setAccomodation',
        'total_price' => 'setTotalPrice',
        'rate' => 'setRate'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'service_class' => 'getServiceClass',
        'booking_code' => 'getBookingCode',
        'accomodation' => 'getAccomodation',
        'total_price' => 'getTotalPrice',
        'rate' => 'getRate'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['service_class'] = isset($data['service_class']) ? $data['service_class'] : null;
        $this->container['booking_code'] = isset($data['booking_code']) ? $data['booking_code'] : null;
        $this->container['accomodation'] = isset($data['accomodation']) ? $data['accomodation'] : null;
        $this->container['total_price'] = isset($data['total_price']) ? $data['total_price'] : null;
        $this->container['rate'] = isset($data['rate']) ? $data['rate'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['service_class'] === null) {
            $invalid_properties[] = "'service_class' can't be null";
        }
        if ($this->container['booking_code'] === null) {
            $invalid_properties[] = "'booking_code' can't be null";
        }
        if ($this->container['accomodation'] === null) {
            $invalid_properties[] = "'accomodation' can't be null";
        }
        if ($this->container['total_price'] === null) {
            $invalid_properties[] = "'total_price' can't be null";
        }
        if ($this->container['rate'] === null) {
            $invalid_properties[] = "'rate' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['service_class'] === null) {
            return false;
        }
        if ($this->container['booking_code'] === null) {
            return false;
        }
        if ($this->container['accomodation'] === null) {
            return false;
        }
        if ($this->container['total_price'] === null) {
            return false;
        }
        if ($this->container['rate'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets service_class
     * @return string
     */
    public function getServiceClass()
    {
        return $this->container['service_class'];
    }

    /**
     * Sets service_class
     * @param string $service_class A standard enumeration of the type of seat, bed or service the passenger can expect.
     * @return $this
     */
    public function setServiceClass($service_class)
    {
        $this->container['service_class'] = $service_class;

        return $this;
    }

    /**
     * Gets booking_code
     * @return string
     */
    public function getBookingCode()
    {
        return $this->container['booking_code'];
    }

    /**
     * Sets booking_code
     * @param string $booking_code A code the identifies the type of booking class being used.
     * @return $this
     */
    public function setBookingCode($booking_code)
    {
        $this->container['booking_code'] = $booking_code;

        return $this;
    }

    /**
     * Gets accomodation
     * @return string
     */
    public function getAccomodation()
    {
        return $this->container['accomodation'];
    }

    /**
     * Sets accomodation
     * @param string $accomodation A standard enumeration of the mode in which the passenger is accommodated. For example&colon; SEAT, BERTH, CABIN, CARGO, UNKNOWN.
     * @return $this
     */
    public function setAccomodation($accomodation)
    {
        $this->container['accomodation'] = $accomodation;

        return $this;
    }

    /**
     * Gets total_price
     * @return \Swagger\Client\Model\Amount
     */
    public function getTotalPrice()
    {
        return $this->container['total_price'];
    }

    /**
     * Sets total_price
     * @param \Swagger\Client\Model\Amount $total_price The total cost of this service.
     * @return $this
     */
    public function setTotalPrice($total_price)
    {
        $this->container['total_price'] = $total_price;

        return $this;
    }

    /**
     * Gets rate
     * @return \Swagger\Client\Model\RestrictedRate
     */
    public function getRate()
    {
        return $this->container['rate'];
    }

    /**
     * Sets rate
     * @param \Swagger\Client\Model\RestrictedRate $rate A rate identifying type of charge being levied for this service, and the restrictions that apply.
     * @return $this
     */
    public function setRate($rate)
    {
        $this->container['rate'] = $rate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


