<?php
/**
 * AffiliateSearchResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AffiliateSearchResultTest Class Doc Comment
 *
 * @category    Class */
// * @description AffiliateSearchResult
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AffiliateSearchResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AffiliateSearchResult"
     */
    public function testAffiliateSearchResult()
    {
    }

    /**
     * Test attribute "outbound"
     */
    public function testPropertyOutbound()
    {
    }

    /**
     * Test attribute "inbound"
     */
    public function testPropertyInbound()
    {
    }

    /**
     * Test attribute "fare"
     */
    public function testPropertyFare()
    {
    }

    /**
     * Test attribute "payout"
     */
    public function testPropertyPayout()
    {
    }

    /**
     * Test attribute "airline"
     */
    public function testPropertyAirline()
    {
    }

    /**
     * Test attribute "deep_link"
     */
    public function testPropertyDeepLink()
    {
    }
}
