<?php
/**
 * FlightSearchSegmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FlightSearchSegmentTest Class Doc Comment
 *
 * @category    Class */
// * @description FlightSearchSegment
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FlightSearchSegmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FlightSearchSegment"
     */
    public function testFlightSearchSegment()
    {
    }

    /**
     * Test attribute "departs_at"
     */
    public function testPropertyDepartsAt()
    {
    }

    /**
     * Test attribute "arrives_at"
     */
    public function testPropertyArrivesAt()
    {
    }

    /**
     * Test attribute "origin"
     */
    public function testPropertyOrigin()
    {
    }

    /**
     * Test attribute "destination"
     */
    public function testPropertyDestination()
    {
    }

    /**
     * Test attribute "marketing_airline"
     */
    public function testPropertyMarketingAirline()
    {
    }

    /**
     * Test attribute "operating_airline"
     */
    public function testPropertyOperatingAirline()
    {
    }

    /**
     * Test attribute "flight_number"
     */
    public function testPropertyFlightNumber()
    {
    }

    /**
     * Test attribute "aircraft"
     */
    public function testPropertyAircraft()
    {
    }

    /**
     * Test attribute "booking_info"
     */
    public function testPropertyBookingInfo()
    {
    }
}
