<?php
/**
 * FlightSearchBookingInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FlightSearchBookingInfoTest Class Doc Comment
 *
 * @category    Class */
// * @description FlightSearchBookingInfo
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FlightSearchBookingInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FlightSearchBookingInfo"
     */
    public function testFlightSearchBookingInfo()
    {
    }

    /**
     * Test attribute "travel_class"
     */
    public function testPropertyTravelClass()
    {
    }

    /**
     * Test attribute "cabin_code"
     */
    public function testPropertyCabinCode()
    {
    }

    /**
     * Test attribute "booking_code"
     */
    public function testPropertyBookingCode()
    {
    }

    /**
     * Test attribute "seats_remaining"
     */
    public function testPropertySeatsRemaining()
    {
    }

    /**
     * Test attribute "fare_family"
     */
    public function testPropertyFareFamily()
    {
    }

    /**
     * Test attribute "fare_basis"
     */
    public function testPropertyFareBasis()
    {
    }
}
