<?php
/**
 * HotelRoomTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * HotelRoomTest Class Doc Comment
 *
 * @category    Class */
// * @description HotelRoom
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HotelRoomTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HotelRoom"
     */
    public function testHotelRoom()
    {
    }

    /**
     * Test attribute "booking_code"
     */
    public function testPropertyBookingCode()
    {
    }

    /**
     * Test attribute "room_type_code"
     */
    public function testPropertyRoomTypeCode()
    {
    }

    /**
     * Test attribute "rate_plan_code"
     */
    public function testPropertyRatePlanCode()
    {
    }

    /**
     * Test attribute "total_amount"
     */
    public function testPropertyTotalAmount()
    {
    }

    /**
     * Test attribute "rates"
     */
    public function testPropertyRates()
    {
    }

    /**
     * Test attribute "descriptions"
     */
    public function testPropertyDescriptions()
    {
    }

    /**
     * Test attribute "room_type_info"
     */
    public function testPropertyRoomTypeInfo()
    {
    }

    /**
     * Test attribute "rate_type_code"
     */
    public function testPropertyRateTypeCode()
    {
    }
}
