<?php
/**
 * HotelPropertyResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * HotelPropertyResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description HotelPropertyResponse
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HotelPropertyResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HotelPropertyResponse"
     */
    public function testHotelPropertyResponse()
    {
    }

    /**
     * Test attribute "property_code"
     */
    public function testPropertyPropertyCode()
    {
    }

    /**
     * Test attribute "property_name"
     */
    public function testPropertyPropertyName()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "total_price"
     */
    public function testPropertyTotalPrice()
    {
    }

    /**
     * Test attribute "min_daily_rate"
     */
    public function testPropertyMinDailyRate()
    {
    }

    /**
     * Test attribute "contacts"
     */
    public function testPropertyContacts()
    {
    }

    /**
     * Test attribute "amenities"
     */
    public function testPropertyAmenities()
    {
    }

    /**
     * Test attribute "awards"
     */
    public function testPropertyAwards()
    {
    }

    /**
     * Test attribute "images"
     */
    public function testPropertyImages()
    {
    }

    /**
     * Test attribute "rooms"
     */
    public function testPropertyRooms()
    {
    }

    /**
     * Test attribute "more_rooms_at_this_hotel"
     */
    public function testPropertyMoreRoomsAtThisHotel()
    {
    }
}
