<?php
/**
 * ImageSizeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ImageSizeTest Class Doc Comment
 *
 * @category    Class */
// * @description An image size selector used in the YapQ API response. The size should correspond the the image_size parameter used during input
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ImageSizeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ImageSize"
     */
    public function testImageSize()
    {
    }

    /**
     * Test attribute "small"
     */
    public function testPropertySmall()
    {
    }

    /**
     * Test attribute "medium"
     */
    public function testPropertyMedium()
    {
    }

    /**
     * Test attribute "large"
     */
    public function testPropertyLarge()
    {
    }

    /**
     * Test attribute "hd"
     */
    public function testPropertyHd()
    {
    }
}
