<?php
/**
 * TrainSearchSegmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Amadeus Travel Innovation Sandbox
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TrainSearchSegmentTest Class Doc Comment
 *
 * @category    Class */
// * @description TrainSearchSegment
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TrainSearchSegmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TrainSearchSegment"
     */
    public function testTrainSearchSegment()
    {
    }

    /**
     * Test attribute "departs_at"
     */
    public function testPropertyDepartsAt()
    {
    }

    /**
     * Test attribute "arrives_at"
     */
    public function testPropertyArrivesAt()
    {
    }

    /**
     * Test attribute "departure_station"
     */
    public function testPropertyDepartureStation()
    {
    }

    /**
     * Test attribute "arrival_station"
     */
    public function testPropertyArrivalStation()
    {
    }

    /**
     * Test attribute "marketing_company"
     */
    public function testPropertyMarketingCompany()
    {
    }

    /**
     * Test attribute "operating_company"
     */
    public function testPropertyOperatingCompany()
    {
    }

    /**
     * Test attribute "train_number"
     */
    public function testPropertyTrainNumber()
    {
    }

    /**
     * Test attribute "train_type"
     */
    public function testPropertyTrainType()
    {
    }

    /**
     * Test attribute "prices"
     */
    public function testPropertyPrices()
    {
    }
}
