var airlinesmain={
    '9W' : 'jetairways.png',
    'AA' : 'americanairline_aa.png',
    'DL' : 'deltaairline_dl.gif',
    'BA' : 'britishairways_ba.jpg',
    'UA' : 'united_tm.jpg',
    'VS': 'virgin-atlantic-airways.gif',
    'NZ':'airnewzealand.gif',
    'SQ':'singapore-airlines.gif',
    'AI':'airindia.jpg',
    'FQ':'thomas-cook.png',
    'KL':'royaldutchairlines.jpg',
    'LH':'lufthansa.jpg',
    'EK':'Emirates.gif',
    'AF':'airfrance.png',
    'AC':'aircanada.gif',
    'EI':'aerlingus.jpg',
    'QR':'qatarairways.jpg',
    'LX':'swissair.jpg',
    'TK':'turkishairlines.jpg',
    'CX':'cathaypacific.gif',
    'SK':'scandinavianairlines.jpg',
    'EY':'Etihad-Airways-Logo.png',
    'IB':'Iberia-Logo.jpg',
    'JL':'japanairlines.png',
    'WR':'WestJet-Logo.jpg',
    'FI':'Icelandair.jpg',
    'AM':'airmexico.jpg',
    'SN':'brusselsairlines.jpg',
    'CA':'airchina.gif',
    'TP':'tap-air-portugal.gif',
    'SU':'aeroflot.gif',
    'KE':'korean-air.gif',
    'XM':'alitalia-express.gif',
    'OZ':'asiana.png',
    'AV':'avianca.gif',
    'BR':'eva.png',
    'QF':'qantas-airways.gif',
    'LY':'El.gif',
    'OS':'austrianairlines.png',
    'AY':'finnair.gif',
    'MU':'chinaeastern.gif',
    'LO':'lot-polish-airlines.gif',
    'NH':'ana.jpg',
    'PR':'philippine-airlines.gif',
    'SV':'saudi-arabian-airlines.gif',
    'CI':'chinaairlines.jpg',
    'AT':'royal-air-maroc.jpg',
    'CZ':'chinasouth.gif',
    'ET':'ethiopia.jpg',
    'UX':'aireuropa.jpg',
    'KU':'kuwait-airways.gif',
    'MS':'egyptair.png',
    'RJ':'royal-jordanian.gif',
    'TS':'air-transat.jpg',
    'PS':'ukraine-international-airlines.jpg',
    'HU':'Hainan-airlines.jpg',
    'EW':'eurowing.png',
    'S4':'sata-international.gif',
    'J2':'azerbaijan_airlines.jpg',
    'JU':'air-serbia.jpg',
    'HY':'uzbekistan-airways.gif',
    'BT':'air-baltic.gif',
    'QJ':'jetairways.png'

}
